version: "3"
services:
  # app:
  # build:
  #   context: ./api/
  #   dockerfile: Dockerfile
  # env_file:
  #   - ./api/environments/db.env
  # # command: bundle exec puma -C config/puma.rb -e production
  # command: bundle exec puma -C config/puma.rb

  # volumes:
  #   - ./api:/webapp
  #   - public-data:/webapp/public
  #   - tmp-data:/webapp/tmp
  #   - log-data:/webapp/log
  # depends_on:
  #   - db

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./api:/myapp
      - ./api/vendor/bundle:/myapp/vendor/bundle
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - 3001:3001
    depends_on:
      - db
  db:
    image: mysql:8.0
    env_file:
      - ./api/environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  # web:
  #   build:
  #     context: ./api/containers/nginx
  #     dockerfile: Dockerfile
  #   volumes:
  #     - public-data:/webapp/public
  #     - tmp-data:/webapp/tmp
  #   ports:
  #     - 3001:80
  #   depends_on:
  #     - app
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/app
    command: sh -c "cd react_front && npm start "
    ports:
      - "80:3000"
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
